# Study Notes: Probability - Counting

**Reference Material:** [Introduction to Probability - Chapter: Counting](https://bookdown.org/probability/beta/counting.html)

## Overview
This notebook serves as a personal study log and code reproduction based on the lecture materials provided in the link above. 

While the core concepts and initial code snippets are transcribed directly from the source text, I have actively incorporated my own modifications, additional annotations, and experimental code blocks. These adjustments were made to deepen my understanding of probability theories and R programming.

*Disclaimer: All foundational theories and original examples belong to the respective authors of the referenced material.*

In [3]:
size = c("S", "M", "L")
topping = c("pepperoni", "sausage", "meatball", "extra cheese")
order = c("deliver", "pick-up")

pizzas = character(0)
# initilize vector

for(i in 1:length(size)){
    for(j in 1:length(topping)){
        for(k in 1:length(order)){
            pizzas = rbind(pizzas, c(size[i], topping[j], order[k]))
            # creat
        }
    }
}

pizzas

      [,1] [,2]         [,3]
 [1,] S    pepperoni    deliver
 [2,] S    pepperoni    pick-up
 [3,] S    sausage      deliver
 [4,] S    sausage      pick-up
 [5,] S    meatball     deliver
 [6,] S    meatball     pick-up
 [7,] S    extra cheese deliver
 [8,] S    extra cheese pick-up
 [9,] M    pepperoni    deliver
[10,] M    pepperoni    pick-up
[11,] M    sausage      deliver
[12,] M    sausage      pick-up
[13,] M    meatball     deliver
[14,] M    meatball     pick-up
[15,] M    extra cheese deliver
[16,] M    extra cheese pick-up
[17,] L    pepperoni    deliver
[18,] L    pepperoni    pick-up
[19,] L    sausage      deliver
[20,] L    sausage      pick-up
[21,] L    meatball     deliver
[22,] L    meatball     pick-up
[23,] L    extra cheese deliver
[24,] L    extra cheese pick-up

In [7]:
# length means the total elements (rows * columns) so we need to devide the amount of columns (= 3)
length(pizzas[pizzas[ ,1] == "L" & pizzas[ ,2] == "sausage"]) / 3

[1] 2

In [15]:
install.packages("combinat")

The downloaded binary packages are in
	/var/folders/8y/mr2dm_jj4k72xtncrxz6f22r0000gn/T//RtmpQB6YWN/downloaded_packages

In [17]:
perms = combinat::permn(c("A", "B", "C", "D", "E", "F", "G"))
head(perms)

[[1]]
[1] "A" "B" "C" "D" "E" "F" "G"

[[2]]
[1] "A" "B" "C" "D" "E" "G" "F"

[[3]]
[1] "A" "B" "C" "D" "G" "E" "F"

[[4]]
[1] "A" "B" "C" "G" "D" "E" "F"

[[5]]
[1] "A" "B" "G" "C" "D" "E" "F"

[[6]]
[1] "A" "G" "B" "C" "D" "E" "F"

In [19]:
length(perms)

[1] 5040

In [21]:
committees = gtools::combinations(n=5, r=3)
committees

      [,1] [,2] [,3]
 [1,] 1    2    3
 [2,] 1    2    4
 [3,] 1    2    5
 [4,] 1    3    4
 [5,] 1    3    5
 [6,] 1    4    5
 [7,] 2    3    4
 [8,] 2    3    5
 [9,] 2    4    5
[10,] 3    4    5

In [25]:
install.packages("gtools")

The downloaded binary packages are in
	/var/folders/8y/mr2dm_jj4k72xtncrxz6f22r0000gn/T//RtmpQB6YWN/downloaded_packages

In [31]:
dim(gtools::permutations(n=6, r=4, repeats.allowed=TRUE))[1]

[1] 1296

In [33]:
dim(gtools::permutations(n=6, r=4, repeats.allowed=FALSE))[1]

[1] 360

In [49]:
uniques = gtools::permutations(n=6, r=4, repeats.allowed=FALSE)

uniques.ascending = apply(uniques, 1, function(x) sort(x))

uniques.ascending = t(uniques.ascending)

uniques.ascending = data.frame(uniques.ascending)

dim(unique(uniques.ascending))[1]

[1] 15

In [51]:
passcodes = gtools::permutations(n=6, r=4, repeats.allowed=TRUE)
ascending = apply(passcodes, 1, function(x) sort(x))

ascending = t(ascending)

ascending = data.frame(ascending)

dim(unique(ascending))[1]

[1] 126

In [55]:
people = 1:4

committees1 = character(0)
for(i in 1:length(people)){
    # select the president (i) and the committees (v = population)
    new.committees = cbind(i, gtools::combinations(n=length(people)-1, r=2, v=people[-i]))
    committees1 = rbind(committees1, new.committees)
}

colnames(committees1) = c("","","")

committees2 = character(0)

# select all committees
new.committees = gtools::combinations(n=4, r=3)

for(i in 1:dim(new.committees)[1]){
    for(j in 1:3){
        # select the president(No.j committee) 
        committees2 = rbind(committees2, c(new.committees[i, j], new.committees[i, -j]))
    }
}

colnames(committees2) = c("", "", "")
committees1

 [1,] 1 2 3
 [2,] 1 2 4
 [3,] 1 3 4
 [4,] 2 1 3
 [5,] 2 1 4
 [6,] 2 3 4
 [7,] 3 1 2
 [8,] 3 1 4
 [9,] 3 2 4
[10,] 4 1 2
[11,] 4 1 3
[12,] 4 2 3

In [57]:
committees2

 [1,] 1 2 3
 [2,] 2 1 3
 [3,] 3 1 2
 [4,] 1 2 4
 [5,] 2 1 4
 [6,] 4 1 2
 [7,] 1 3 4
 [8,] 3 1 4
 [9,] 4 1 3
[10,] 2 3 4
[11,] 3 2 4
[12,] 4 2 3

In [63]:
set.seed(110)
sims = 1000

deck = c(rep(1, 13), rep(0, 52 - 13))

spades = rep(NA, sims)

for (i in  1:sims){
    hand = sample(deck, 4, replace = FALSE)
    spades[i] = sum(hand)
}

mean(spades)

[1] 0.978